version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: springboot-api-postgres-c
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/data/postgres
    volumes:
      - springboot-api-postgres:/data/postgres
    ports:
      - "5332:5432"
  docker-redis:
    image: redis:7-alpine
    container_name: springboot-api-redis-c
    ports:
      - "6379:6379"
    volumes:
      - springboot-api-redis:/data

volumes:
  springboot-api-postgres:
  springboot-api-redis: